export { isAuthenticated } from './auth'
export { init } from './init'
export { getDashAccount, registerIdentity } from './dash'
export { getMnemonic } from './storage'
export { getAvatarString } from './string'
